### ISSUE TITLE
Website banner obscures header at certain widths

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/Endings#2]
(I'm submitting this issue here since I can't leave an issue on the actual projectendings.github.io repository.)

Was just looking at the projectendings.github.io website and noticed that at particular widths (768px-1013px to be exact), the banner/topnav thing obscures the first heading on a page. Some examples:

![screen shot 2019-02-08 at 9 13 00 pm](https://user-images.githubusercontent.com/17664763/52516830-67798380-2be6-11e9-8e45-6127d75becb4.png)
![screen shot 2019-02-08 at 9 12 40 pm](https://user-images.githubusercontent.com/17664763/52516832-6b0d0a80-2be6-11e9-8b82-58db8e09dcbb.png)

This is on Chrome, but it seems to happen on every browser (Firefox, Safari, and Opera).

**Comment by martindholmes** [comment]
Yes, it looks like you can make it do that by setting a width that's small enough to make it wrap, but not small enough to trigger the other menu format for small-factor devices. It's Bootstrap. @jmhuculak  knows how it works -- Matt, what do you think? Dump the Bootstrap crap and write some straightforward CSS?

**Comment by jmhuculak** [comment]
I say we just simply the menu. Easy. Quick. Less clutter.

**Comment by martindholmes** [comment]
Simply what the menu?

**Comment by jmhuculak** [comment]
urgh. "Simplify" the menu. Put "conference papers" and Journals under "resources"

**Comment by joeytakeda** [comment]
If you simplify the menu, I would also suggest getting rid of the "Us" in "Contact Us" and "About Us" :-)

**Comment by jmhuculak** [comment]
Yeah. Good call on that, too.

**Comment by jmhuculak** [comment]
Okay, I've shortened the menu. Hopefully, this solves the problem. Joey?

**Comment by joeytakeda** [comment]
Yep, looks good to me! Thanks
